[package]
name = "uroborosql-lint"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
globset = "0.4"
ignore = "0.4"
postgresql-cst-parser = { workspace = true }

[dev-dependencies]
tempfile = "3"
